steps:
  # 构建 Docker 镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
     '-t', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}', 
     '-f', 'Dockerfile','.']
  # 将 Docker 镜像推送到 Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: 
      - apply
      - -f
      - kubernetes/deployment.yaml
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1' # 替换为您的 GKE 集群所在区域
      - 'CLOUDSDK_CONTAINER_CLUSTER=blueturbo-gke-test' # 替换为您的 GKE 集群名称
  - name: 'gcr.io/cloud-builders/kubectl'
    args: 
      - set
      - image
      - deployment/vector-deployment
      - vector-container=${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1' # 替换为您的 GKE 集群所在区域
      - 'CLOUDSDK_CONTAINER_CLUSTER=blueturbo-gke-test' # 替换为您的 GKE 集群名称
  # 将应用程序部署到 GKE
  # - name: 'gcr.io/cloud-builders/gke-deploy'
  #   args:
  #     - apply
  #     - -f
  #     - kubernetes/deployment.yaml # 您的 Kubernetes 部署文件
  #     - -f
  #     - kubernetes/service.yaml # 您的 Kubernetes 服务文件
  #   env:
  #     - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1' # 替换为您的 GKE 集群所在区域
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=blueturbo-gke-test' # 替换为您的 GKE 集群名称
# 替换以下值
substitutions:
    _LOCATION: asia-southeast1 # 例如 us-central1
    _PROJECT_ID: blueturbo # 您的 GCP 项目 ID
    _REPOSITORY: blueturbo-dsp-server # ar镜像仓库
    _IMAGE: dsp_vector # 例如 my-app
    _TAG: $COMMIT_SHA # 使用提交哈希作为标签

images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}'

logsBucket: gs://blueturbo_dsp_logs_sg # 替换为您的日志存储桶