# Source: Collect logs from a specific file path
[
sources.system_logger
]
type = "file"
include = ["/var/log/system_logger*.log"]  # 假设日志文件挂载到此路径


[
sources.framework_logger
]
type = "file"
include = ["/var/log/framework_logger*.log"]

[
sources.bid_logger
]
type = "file"
include = ["/var/log/bid_logger*.log"]

# Sink: Send logs to Kafka
[
sinks.out_to_kafka
]
type = "kafka"
inputs = ["bid_logs"]
bootstrap_servers = "bootstrap.blueturbo-sg-kafka.asia-southeast1.managedkafka.blueturbo.cloud.goog:9092"  # Replace with your Kafka broker address
topic = "__remote_log_metadata"  # Replace with your Kafka topic
encoding.codec = "json"  # Send logs in JSON format