apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
  namespace: dsp-ns
  labels:
    app: vector
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      containers:
      - name: vector-container
        image: $IMAGE
        volumeMounts:
          - name: dsp-server-storage
            mountPath: /logs  # Container path where logs will be available
        ports:
        - containerPort: 9000   # 容器监听的端口
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:  # 确保这里的缩进与 containers 对齐
      - name: dsp-server-storage
        persistentVolumeClaim:
          claimName: dsp-server-pvc
