apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
  namespace: dsp-ns
spec:
  replicas: 1  # 指定应用的副本数
  selector:
    matchLabels:
      app: v
  template:
    metadata:
      labels:
        app: vector
    spec:
      containers:
      - name: vector-container
        image: $IMAGE
        volumeMounts:
          - name: dsp-server-storage
            mountPath: /logs  # Container path where logs will be available
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:  # 确保这里的缩进与 containers 对齐
      - name: dsp-server-storage
        persistentVolumeClaim:
          claimName: dsp-server-pvc
