apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-deployment
  namespace: dsp-ns
  labels:
    app: vector
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dsp-bid-server
            topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - vector
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: vector-container
        image: $IMAGE
        volumeMounts:
          - name: dsp-server-storage
            mountPath: /logs  # Container path where logs will be available
        ports:
        - containerPort: 9000  # 容器监听的端口
          protocol: TCP
        resources:
          requests:
            memory: "2048Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
      volumes:  # 确保这里的缩进与 containers 对齐
      - name: dsp-server-storage
        persistentVolumeClaim:
          claimName: dsp-server-pvc
